Repository elastisys/welkin, pull requests merged in 2024-05, with the labels that each got.

#862 docs: typo in log-review page
  docs/ciso-guide/log-review.md
Labels: documentation

#849 docs: update velero restore commands to be more consistent
  docs/operator-manual/disaster-recovery.md
Labels: documentation

#866 pre-commit: Disable commit-to-branch in workflow
  .github/workflows/lint.yml
Labels: bug

#865 docs: Add section about wc prometheus access
  docs/user-guide/metrics.md
Labels: documentation

#868 Run pre-commit
  docs/mission-and-vision.md
Labels: bug

#874 Auto-generate docs from JSON schema
  .github/workflows/deploy.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/operator-manual/schema/README.md
  docs/operator-manual/schema/config.md
  docs/operator-manual/schema/secrets.md
  mkdocs.yml
  package-lock.json
  package.json
  scripts/jsonschema2md.sh
Labels: enhancement

#875 hnc how to delete subnamespaces
  docs/user-guide/namespaces.md
Labels: documentation
