Repository elastisys/welkin, pull requests merged in 2025-04, with the labels that each got.

#1097 Docs: fix typos / grammar / markdown markup after proofreading
  docs/adr/0050-use-cluster-isolation.md
  docs/adr/0053-do-not-expose-platform-observability-services-to-end-users.md
  docs/operator-manual/break-glass.md
  docs/operator-manual/credentials.md
  docs/operator-manual/maintenance.md
  docs/operator-manual/on-prem-standard.md
  docs/operator-manual/provider-audit.md
  docs/operator-manual/understand-welkin.md
Labels: enhancement

#1098 docs: fix more typos / grammar / md after proofreading
  docs/adr/0004-plan-for-usage-without-wrapper-scripts.md
  docs/adr/0005-use-individual-ssh-keys.md
  docs/adr/0006-use-standard-kubeconfig-mechanisms.md
  docs/adr/0007-make-monitoring-forwarders-storage-independent.md
  docs/adr/0009-use-cluster-issuers-for-letsencrypt.md
  docs/adr/0012-do-not-persist-dex.md
  docs/adr/0015-we-believe-in-community-driven-open-source.md
  docs/adr/0016-gid-0-is-okey-but-not-by-default.md
  docs/adr/0017-persist-dex.md
  docs/adr/0024-allow-Harbor-robot-account.md
  docs/adr/0025-local-storage.md
  docs/adr/0029-expose-jaeger-ui.md
  docs/adr/0030-run-argocd-on-elastisys-nodes.md
  docs/adr/0031-run-csi-cinder-controllerplugin-on-elastisys-nodes.md
  docs/adr/0032-boot-disk-size.md
  docs/adr/0033-run-cluster-api-controllers-on-service-cluster.md
  docs/adr/0034-how-to-run-multiple-ams-packages-of-the-same-type.md
  docs/adr/0036-run-ingress-nginx-as-daemonset.md
  docs/adr/0037-enforce-ttl-on-jobs.md
  docs/adr/0038-replace-starboard-operator-with-trivy-operator.md
  docs/adr/0039-application-dev-permissions.md
  docs/adr/0041-encryption-at-rest.md
  docs/adr/0042-argocd-dynamic-hnc-namespaces.md
  docs/adr/0045-use-specialised-prebuilt-images.md
  docs/adr/0046-handle-crds.md
  docs/adr/0047-kubernetes-versions.md
  docs/adr/0048-access-management-for-AMS-with-network-policies.md
  docs/adr/0050-use-cluster-isolation.md
Labels: documentation, enhancement, not-planned

#1104 docs: internal lb
  docs/user-guide/network-model.md
Labels: documentation
